In [1]:
import numpy as np
from collections import OrderedDict
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import torch
from tqdm import tqdm
from torch import nn, optim
from torch.nn import functional as F
from torch.nn.parameter import Parameter
from torch import FloatTensor
from torch.autograd import Variable

In [2]:
EPOCHS_TO_TRAIN = 5000
class XOR(nn.Module):
    def __init__(self, initialize=False):
      super(XOR, self).__init__()
      self.fc1 = nn.Linear(2, 2, True)
      self.fc2 = nn.Linear(2, 1, True)
      if initialize:
        self.weights_initialization()

    def weights_initialization(self): # Unindent this method to be at the same level as forward
      with torch.no_grad():
        self.fc1.weight.copy_(torch.tensor([[-1, 1], [1, -1]], dtype=torch.float))
        self.fc1.bias.copy_(torch.tensor([0, 0], dtype=torch.float))
        self.fc2.weight.copy_(torch.tensor([1, 1], dtype=torch.float))
        self.fc2.bias.copy_(torch.tensor([0], dtype=torch.float))

    def forward(self, x): # The forward method starts here
      x = F.relu(self.fc1(x))
      x = self.fc2(x)
      return x



model = XOR(True)
x = list(map(lambda s: Variable(torch.Tensor([s])), [
 [0, 0],
 [0, 1],
 [1, 0],
 [1, 1]
]))
y = list(map(lambda s: Variable(torch.Tensor([s])), [
  [0],
  [1],
  [1],
  [0]
]))

In [3]:
list(model.named_parameters())

[('fc1.weight',
  Parameter containing:
  tensor([[-1.,  1.],
          [ 1., -1.]], requires_grad=True)),
 ('fc1.bias',
  Parameter containing:
  tensor([0., 0.], requires_grad=True)),
 ('fc2.weight',
  Parameter containing:
  tensor([[1., 1.]], requires_grad=True)),
 ('fc2.bias',
  Parameter containing:
  tensor([0.], requires_grad=True))]

In [4]:
print("")
correct = 0
print("Final results:")
for input, target in zip(x, y):
  output = model(input)
  print("Input:[{},{}] Target:[{}] Predicted:[{}] Error:[{}]".format(
  int(input.data.numpy()[0][0]),
  int(input.data.numpy()[0][1]),
  int(target.data.numpy()),
  round(float(output.data.numpy()), 4),
  round(float(abs(target.data.numpy() - output.data.numpy())), 4)
  ))
  if target.data.numpy() == round(float(output.data.numpy()), 2):
      correct +=1
print(f'{correct} correct')


Final results:
Input:[0,0] Target:[0] Predicted:[0.0] Error:[0.0]
Input:[0,1] Target:[1] Predicted:[1.0] Error:[0.0]
Input:[1,0] Target:[1] Predicted:[1.0] Error:[0.0]
Input:[1,1] Target:[0] Predicted:[0.0] Error:[0.0]
4 correct


<ipython-input-4-303dc17a013e>:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  int(target.data.numpy()),
<ipython-input-4-303dc17a013e>:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  round(float(output.data.numpy()), 4),
<ipython-input-4-303dc17a013e>:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  round(float(abs(target.data.numpy() - output.data.numpy())), 4)
<ipython-input-4-303dc17a013e>:13: DeprecationWarning: Conversion of an array with ndim > 0 to a sc

In [5]:
model = XOR()

In [6]:
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)
losses = []
print("Training loop:")
for idx in tqdm(range(0, EPOCHS_TO_TRAIN)):
  losss = []
  for input, target in zip(x, y):
      optimizer.zero_grad() # zero the gradient buffers
      output = model(input)
      loss = criterion(output, target)
      loss.backward()
      optimizer.step() # Does the update
      losss.append(loss.data.numpy())
      losses.append(np.mean(losss))
 # if idx % 100 == 0:
 # print("Epoch {: >8} Loss: {}".format(idx, loss.data.numpy()))

Training loop:


100%|██████████| 5000/5000 [00:17<00:00, 279.89it/s]


In [7]:
print("")
correct = 0
print("Final results:")
for input, target in zip(x, y):
  output = model(input)
  print("Input:[{},{}] Target:[{}] Predicted:[{}] Error:[{}]".format(
    int(input.data.numpy()[0][0]),
    int(input.data.numpy()[0][1]),
    int(target.data.numpy()),
    round(float(output.data.numpy()), 4),
    round(float(abs(target.data.numpy() - output.data.numpy())), 4)
  ))

  if target.data.numpy() == round(float(output.data.numpy()), 2):
      correct +=1
print(f'{correct} correct')


Final results:
Input:[0,0] Target:[0] Predicted:[0.4999] Error:[0.4999]
Input:[0,1] Target:[1] Predicted:[0.4999] Error:[0.5001]
Input:[1,0] Target:[1] Predicted:[0.4999] Error:[0.5001]
Input:[1,1] Target:[0] Predicted:[0.4999] Error:[0.4999]
0 correct


<ipython-input-7-b42ebab38cce>:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  int(target.data.numpy()),
<ipython-input-7-b42ebab38cce>:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  round(float(output.data.numpy()), 4),
<ipython-input-7-b42ebab38cce>:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  round(float(abs(target.data.numpy() - output.data.numpy())), 4)
<ipython-input-7-b42ebab38cce>:14: DeprecationWarning: Conversion of an array with ndim > 0 to a sc

In [8]:
for (name, value) in model.named_parameters():
 print(f"{name} = {value.detach().numpy()}")

fc1.weight = [[-0.16693532  0.51412386]
 [-0.22119889  0.62013286]]
fc1.bias = [-0.66322726 -0.6834901 ]
fc2.weight = [[-0.43084294  0.00288554]]
fc2.bias = [0.49989748]
